local DB      = exports['lw-db']:DB()
local LWUtils = exports['lw-shared']:GetUtils()

-- ---------------------------------------------------------------------------
-- Internal helpers
-- ---------------------------------------------------------------------------

---@param  stateId  string
---@return          table|nil
local function FetchCharacter(stateId)
    return DB.single(
        'SELECT * FROM `lw_characters` WHERE `state_id` = ?',
        { stateId }
    )
end

-- ---------------------------------------------------------------------------
-- Module-level functions
-- Accessible to other server scripts in this resource (main.lua).
-- ---------------------------------------------------------------------------

--- Writes the character's last known position to the database.
--- Called by the periodic save loop and on character unload.
--- Must be called from within a Citizen.CreateThread.
---@param  stateId  string
---@param  coords   vector3
---@param  heading  number
function SaveLocation(stateId, coords, heading)
    DB.update([[
        UPDATE `lw_characters`
        SET    `last_x` = ?, `last_y` = ?, `last_z` = ?, `last_heading` = ?
        WHERE  `state_id` = ?
    ]], { coords.x, coords.y, coords.z, heading, stateId })
end

-- ---------------------------------------------------------------------------
-- Export implementations
-- ---------------------------------------------------------------------------

---@param  stateId  string
---@return          table|nil
local function GetCharacter(stateId)
    return FetchCharacter(stateId)
end

---@param  source  integer
---@return         table|nil
local function GetActiveCharacter(source)
    local session = exports['lw-core']:GetPlayer(source)
    if not session or not session.stateId then return nil end
    return FetchCharacter(session.stateId)
end

--- Ordered by last_played_at descending for consistent selection scene ordering.
---@param  license2  string
---@return           table[]
local function GetCharactersByLicense2(license2)
    return DB.query(
        'SELECT * FROM `lw_characters` WHERE `license2` = ? ORDER BY `last_played_at` DESC',
        { license2 }
    )
end

--- Used by lw-mortality on server start to rebuild corpse NPCs at last known position.
---@return  table[]
local function GetDeceasedCharacters()
    return DB.query(
        'SELECT * FROM `lw_characters` WHERE `status` = ?',
        { LWUtils.Enums.CharacterStatus.Deceased }
    )
end

--- stateId must be pre-generated by lw-core via RequestStateId.
--- Validates name availability before insert.
--- Must be called from within a Citizen.CreateThread.
---@param  license2  string
---@param  data      table    { stateId, firstName, lastName }
---@return           boolean  success
---@return           string|nil  error message
local function CreateCharacter(license2, data)
    if not data.stateId or not data.firstName or not data.lastName then
        return false, 'Missing required fields: stateId, firstName, lastName.'
    end

    if not IsNameAvailable(license2, data.firstName, data.lastName) then
        return false, 'Name is already in use on this account.'
    end

    local id = DB.insert([[
        INSERT INTO `lw_characters` (`state_id`, `license2`, `first_name`, `last_name`)
        VALUES (?, ?, ?, ?)
    ]], { data.stateId, license2, data.firstName, data.lastName })

    if not id then return false, 'Database insert failed.' end

    TriggerEvent('lw-characters-api:characterCreated', license2, data.stateId)
    return true
end

--- Only whitelisted fields are touched.
--- Status changes must go through SetCharacterStatus or SetCharacterDeceased.
--- Must be called from within a Citizen.CreateThread.
---@param  stateId  string
---@param  data     table    Any subset of { first_name, last_name }
---@return          boolean
local function UpdateCharacter(stateId, data)
    local allowed = { first_name = true, last_name = true }
    local sets    = {}
    local params  = {}

    for key, value in pairs(data) do
        if allowed[key] then
            sets[#sets + 1]    = ('`%s` = ?'):format(key)
            params[#params + 1] = value
        end
    end

    if #sets == 0 then return false end

    params[#params + 1] = stateId

    local affected = DB.update(
        ('UPDATE `lw_characters` SET %s WHERE `state_id` = ?'):format(table.concat(sets, ', ')),
        params
    )

    return affected > 0
end

--- Use SetCharacterDeceased for permadeath — it handles tombstone creation atomically.
--- Must be called from within a Citizen.CreateThread.
---@param  stateId  string
---@param  status   string  LWUtils.Enums.CharacterStatus value
---@return          boolean
local function SetCharacterStatus(stateId, status)
    local valid = false
    for _, v in pairs(LWUtils.Enums.CharacterStatus) do
        if v == status then valid = true break end
    end
    if not valid then return false end

    local char = FetchCharacter(stateId)
    if not char then return false end

    local affected = DB.update(
        'UPDATE `lw_characters` SET `status` = ? WHERE `state_id` = ?',
        { status, stateId }
    )

    if affected > 0 then
        TriggerEvent('lw-characters-api:characterStatusChanged', stateId, status, char.status)
        return true
    end

    return false
end

--- Atomically transitions a character to Deceased and writes their tombstone.
--- Validates epitaph length. No epitaph means no memorial entry — tombstone
--- still written for name lock purposes.
--- Must be called from within a Citizen.CreateThread.
---@param  stateId  string
---@param  epitaph  string|nil
---@return          boolean     success
---@return          string|nil  error message
local function SetCharacterDeceased(stateId, epitaph)
    if epitaph and #epitaph > Config.MaxEpitaphLength then
        return false, ('Epitaph exceeds maximum length of %d characters.'):format(Config.MaxEpitaphLength)
    end

    local char = FetchCharacter(stateId)
    if not char then return false, 'Character not found.' end

    if char.status == LWUtils.Enums.CharacterStatus.Deceased then
        return false, 'Character is already deceased.'
    end

    local ok = DB.transaction({
        {
            query  = 'UPDATE `lw_characters` SET `status` = ?, `deceased_at` = CURRENT_TIMESTAMP WHERE `state_id` = ?',
            values = { LWUtils.Enums.CharacterStatus.Deceased, stateId },
        },
        {
            query  = [[
                INSERT INTO `lw_character_tombstones`
                    (`state_id`, `license2`, `first_name`, `last_name`, `epitaph`)
                VALUES
                    (?, ?, ?, ?, ?)
            ]],
            values = { stateId, char.license2, char.first_name, char.last_name, epitaph },
        },
    })

    if not ok then return false, 'Transaction failed.' end

    TriggerEvent('lw-characters-api:characterStatusChanged', stateId, LWUtils.Enums.CharacterStatus.Deceased, char.status)
    return true
end

--- Hard deletes a character row. CASCADE handles all extension table cleanup.
--- No tombstone is written — this is for forced pruning only.
--- lw-mortality uses SetCharacterDeceased followed by DeleteCharacter after 7 days.
--- Must be called from within a Citizen.CreateThread.
---@param  stateId  string
---@return          boolean
local function DeleteCharacter(stateId)
    local affected = DB.update(
        'DELETE FROM `lw_characters` WHERE `state_id` = ?',
        { stateId }
    )

    if affected > 0 then
        TriggerEvent('lw-characters-api:characterDeleted', stateId)
        return true
    end

    return false
end

---@param  stateId  string
---@param  coords   vector3
---@param  heading  number
local function SaveLocationExport(stateId, coords, heading)
    CreateThread(function()
        SaveLocation(stateId, coords, heading)
    end)
end

-- ---------------------------------------------------------------------------
-- Export registration
-- ---------------------------------------------------------------------------
exports('GetCharacter',          GetCharacter)
exports('GetActiveCharacter',    GetActiveCharacter)
exports('GetCharactersByLicense2', GetCharactersByLicense2)
exports('GetDeceasedCharacters', GetDeceasedCharacters)
exports('CreateCharacter',       CreateCharacter)
exports('UpdateCharacter',       UpdateCharacter)
exports('SetCharacterStatus',    SetCharacterStatus)
exports('SetCharacterDeceased',  SetCharacterDeceased)
exports('DeleteCharacter',       DeleteCharacter)
exports('SaveLocation',          SaveLocationExport)